### PR TITLE
Update README to mention relationship with CB-TB

### PR DESCRIPTION
**Pull request by seokho-son**
a playground PR to test https://github.com/cloud-barista/cm-beetle/pull/20 works

;)

`/approve`

### CODE REVIEW

**Comment by seokho-son** [comment]
on debugging .. ;)
https://github.com/cloud-barista/cm-beetle/actions/runs/6874046394

**Comment by yunkon-kim** [comment]
Would the link below be helpful?
https://docs.github.com/en/rest/teams/members?apiVersion=2022-11-28#list-team-members

> curl -L \
>  -H "Accept: application/vnd.github+json" \
>  -H "Authorization: Bearer <YOUR-TOKEN>" \
>  -H "X-GitHub-Api-Version: 2022-11-28" \
>  https://api.github.com/orgs/ORG/teams/TEAM_SLUG/members

**Comment by seokho-son** [comment]
> Would the link below be helpful? https://docs.github.com/en/rest/teams/members?apiVersion=2022-11-28#list-team-members
> 
> > curl -L 
> > -H "Accept: application/vnd.github+json" 
> > -H "Authorization: Bearer " 
> > -H "X-GitHub-Api-Version: 2022-11-28" 
> > https://api.github.com/orgs/ORG/teams/TEAM_SLUG/members
> 
> In our case,
> 
> ```
> TEAM_MEMBERS=$(curl -L \
>                           -H "Accept: application/vnd.github+json" \
>                           -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
>                           -H "X-GitHub-Api-Version: 2022-11-28" \
>                           https://api.github.com/orgs/cloud-barista/teams/${TEAM_NAME}/members | jq -r '.[] | .login')
> ```

GPT 혼내는 중.. ;)

**Pull request merged**
